"""Adicionando tabela Despesas 3

Revision ID: 37b9e0cd6aef
Revises: 56b5a563e1ce
Create Date: 2024-11-12 15:33:17.547531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b9e0cd6aef'
down_revision: Union[str, None] = '56b5a563e1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
