"""create complementary_exams tables

Revision ID: 3b558a63d02f
Revises: aba9c4cfd5ca
Create Date: 2024-08-23 15:40:49.156453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b558a63d02f'
down_revision: Union[str, None] = 'aba9c4cfd5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physiotherapy_diagnosis',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_details', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physiotherapy_diagnosis')
    # ### end Alembic commands ###
