"""create treatment_plan table

Revision ID: 5415c0d1086e
Revises: a63727eaa9ca
Create Date: 2024-08-27 14:33:21.785194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5415c0d1086e'
down_revision: Union[str, None] = 'a63727eaa9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatments_plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('objectives', sa.String(), nullable=False),
    sa.Column('probable_sessions', sa.Integer(), nullable=False),
    sa.Column('procedures', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatments_plan')
    # ### end Alembic commands ###
