"""Adicionando tabela Despesas 2

Revision ID: 56b5a563e1ce
Revises: f2fd1af479df
Create Date: 2024-11-12 14:53:53.530107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b5a563e1ce'
down_revision: Union[str, None] = 'f2fd1af479df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
