"""create base login

Revision ID: 9cfdc28bdff5
Revises: 5415c0d1086e
Create Date: 2024-10-11 13:23:06.951103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfdc28bdff5'
down_revision: Union[str, None] = '5415c0d1086e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physiotherapy_diagnosis')
    op.drop_table('prognosis')
    op.drop_table('clinical_histories')
    op.drop_table('treatments_plan')
    op.drop_table('complementary_exams')
    op.drop_table('patients')
    op.drop_table('clinical_examinations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_examinations',
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_details', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('place_of_birth', sa.VARCHAR(), nullable=False),
    sa.Column('marital_status', sa.VARCHAR(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=False),
    sa.Column('profession', sa.VARCHAR(), nullable=False),
    sa.Column('residential_address', sa.VARCHAR(), nullable=False),
    sa.Column('commercial_address', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complementary_exams',
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_details', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('treatments_plan',
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('objectives', sa.VARCHAR(), nullable=False),
    sa.Column('probable_sessions', sa.INTEGER(), nullable=False),
    sa.Column('procedures', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('clinical_histories',
    sa.Column('history_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('main_complaint', sa.VARCHAR(), nullable=False),
    sa.Column('disease_history', sa.VARCHAR(), nullable=False),
    sa.Column('lifestyle_habits', sa.VARCHAR(), nullable=False),
    sa.Column('previous_treatments', sa.VARCHAR(), nullable=False),
    sa.Column('personal_family_history', sa.VARCHAR(), nullable=False),
    sa.Column('other_information', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('prognosis',
    sa.Column('prognosis_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('prognosis_details', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('prognosis_id')
    )
    op.create_table('physiotherapy_diagnosis',
    sa.Column('diagnosis_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('diagnosis_details', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    # ### end Alembic commands ###
