"""Adicionando tabela Despesas salvar arquivo

Revision ID: ad04ca5730fd
Revises: 37b9e0cd6aef
Create Date: 2024-11-13 10:05:51.536456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad04ca5730fd'
down_revision: Union[str, None] = '37b9e0cd6aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('grupo_de_gasto', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('despesas', 'grupo_de_gasto')
    # ### end Alembic commands ###
