"""create clinical_histories table

Revision ID: babb6ea36ba2
Revises: 6864f1de9bf2
Create Date: 2024-08-21 13:48:42.928482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babb6ea36ba2'
down_revision: Union[str, None] = '6864f1de9bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_histories',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('main_complaint', sa.String(), nullable=False),
    sa.Column('disease_history', sa.String(), nullable=False),
    sa.Column('lifestyle_habits', sa.String(), nullable=False),
    sa.Column('previous_treatments', sa.String(), nullable=False),
    sa.Column('personal_family_history', sa.String(), nullable=False),
    sa.Column('other_information', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_histories')
    # ### end Alembic commands ###
