"""Adicionando tabela Despesas

Revision ID: f2fd1af479df
Revises: aa257488d6bd
Create Date: 2024-11-12 14:17:36.105319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fd1af479df'
down_revision: Union[str, None] = 'aa257488d6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subelemento', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('processo', sa.String(), nullable=False),
    sa.Column('favorecido', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('acao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    # ### end Alembic commands ###
